.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. myriadcoin_qt test_myriadcoin_qt
clean: FORCE
	$(MAKE) -C .. myriadcoin_qt_clean test_myriadcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_myriadcoin_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. myriadcoin_qt
